# Generated by Django 5.1 on 2025-10-23 19:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_subject', models.CharField(help_text='Email subject for threading', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cold', 'Cold'), ('complete', 'Complete')], default='active', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('agreed_to_free_class', 'Agreed to Free Class'), ('not_interested', 'Not Interested'), ('reached_message_limit', 'Reached Message Limit')], max_length=30, null=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_interval_minutes', models.IntegerField(default=5)),
                ('cold_lead_threshold_days', models.IntegerField(default=7)),
                ('cold_lead_notifications_enabled', models.BooleanField(default=False)),
                ('max_message_exchanges', models.IntegerField(default=10)),
                ('llm_provider_primary', models.CharField(default='grok', max_length=20)),
                ('llm_provider_fallback', models.CharField(default='openai', max_length=20)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('prospect', 'Prospect'), ('llm_generated', 'LLM Generated'), ('sent', 'Sent')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_content', models.TextField(help_text='Original LLM-generated content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=20)),
                ('edited_content', models.TextField(blank=True, help_text='Content after human editing', null=True)),
                ('llm_provider', models.CharField(default='grok', help_text='Which LLM generated this', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_responses', to='leads.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='leads.prospect'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('prospect', 'thread_subject')},
        ),
    ]
