# Generated by Django 5.1 on 2025-10-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='detected_intent',
            field=models.CharField(blank=True, choices=[('weight_loss', 'WEIGHT_LOSS'), ('stress_relief_mental_health', 'STRESS_RELIEF'), ('learn_boxing_technique', 'BOXING_TECHNIQUE'), ('general_fitness', 'GENERAL_FITNESS'), ('social_community', 'SOCIAL_COMMUNITY'), ('just_wants_free_class', 'JUST_FREE_CLASS')], help_text='Intent detected by sales LLM', max_length=50, null=True),
        ),
    ]
