# Generated by Django 5.1 on 2025-10-25 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_conversation_detected_intent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A human-readable name for this prompt group.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='What is the purpose of this prompt?')),
            ],
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1, help_text='The internal version number for this prompt set (e.g., 1, 2, 3).')),
                ('prompt_text', models.TextField(help_text='The actual, complete text of the prompt to be sent to the LLM.')),
                ('is_active', models.BooleanField(default=False, help_text='Only one version should be active at a time for a given PromptSet.')),
                ('is_production', models.BooleanField(default=False, help_text='Marks this version as approved for production deployment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prompt_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='leads.promptset')),
            ],
        ),
    ]
