# Generated by Django 5.1 on 2025-10-25 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_promptset_promptversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A human-readable name for this prompt group.', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='promptversion',
            name='prompt_set',
        ),
        migrations.RemoveField(
            model_name='promptversion',
            name='created_by',
        ),
        migrations.CreateModel(
            name='SystemPromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The complete text of the prompt for this version.')),
                ('version', models.PositiveIntegerField(help_text='The sequential version number (e.g., 1, 2, 3).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text="A brief explanation of why this version was created (e.g., 'Fixed tone', 'Added JSON output requirement').")),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this version.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(help_text='The logical prompt set this version belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='leads.systemprompt')),
            ],
            options={
                'ordering': ['prompt', 'version'],
                'unique_together': {('prompt', 'version')},
            },
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='active_version',
            field=models.ForeignKey(blank=True, help_text='The currently active version of the prompt content.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.systempromptversion'),
        ),
        migrations.DeleteModel(
            name='PromptSet',
        ),
        migrations.DeleteModel(
            name='PromptVersion',
        ),
    ]
