# Generated by Django 5.1 on 2025-10-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_systemprompt_remove_promptversion_prompt_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='detected_intent',
        ),
        migrations.AddField(
            model_name='conversation',
            name='intent',
            field=models.CharField(blank=True, help_text='Simplified intent for quick filtering', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='llm_determined_intent',
            field=models.JSONField(blank=True, help_text='Full LLM intent determination as structured data', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='llm_determined_outcome',
            field=models.JSONField(blank=True, help_text='Full LLM outcome determination as structured data', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='outcome',
            field=models.CharField(blank=True, help_text='Simplified outcome for quick filtering', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'last_message_at'], name='leads_conve_status_dc9a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['intent'], name='leads_conve_intent_b61c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['outcome'], name='leads_conve_outcome_165643_idx'),
        ),
    ]
