# Generated by Django 5.1 on 2025-10-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_conversation_detected_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='intent',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight loss'), ('stress_relief_mental_health', 'Stress relief / mental health'), ('learn_boxing_technique', 'Learn boxing technique'), ('general_fitness', 'General fitness'), ('social_community', 'Social / community'), ('just_wants_free_class', 'Just wants free class')], help_text='Simplified intent for quick filtering', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='outcome',
            field=models.CharField(blank=True, choices=[('agreed_to_free_class', 'Agreed to free class'), ('not_interested', 'Not interested'), ('reached_message_limit', 'Reached message limit'), ('continue', 'Continue conversation')], help_text='Simplified outcome for quick filtering', max_length=50, null=True),
        ),
    ]
